_base_ = '../faster_rcnn/faster_rcnn_r101_fpn_1x_coco.py'
model = dict(
    neck=dict(
        type='AwareFPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
)
train_cfg=dict( 
    rcnn=dict(
        assigner=dict(
            type='GroupAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.5,
            min_pos_iou=0.5,
            match_low_quality=False,
            ignore_iof_thr=-1),
        sampler=dict(
            type='RandomSampler',
            num=512,
            pos_fraction=0.25,
            neg_pos_ub=-1,
            add_gt_as_proposals=True),
        pos_weight=-1,
        debug=False))
